name: sample-workflow
on:
  push:
    branches: [master]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: checks-out yours repository under $GITHUB-WORKSPACE
      uses: actions/checkout@v2
    - name: use echo command
      run: echo "sample-workflow"
